on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-18.04
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: animalie
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer self-update --stable
 
    - name: Prepare Laravel Application
      run: |
        cp .env.main .env
        php artisan key:generate
 
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/
